kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang
  commands:
  - go build
  - go test

- name: build-image
  image: plugins/docker
  settings:
    repo: rg.nl-ams.scw.cloud/revlabs/dcron