kind: pipeline
type: docker
name: default

steps:
- name: Build and Test
  image: golang
  commands:
  - go build
  - go test

- name: Build image and publish
  image: plugins/docker
  settings:
    repo: rg.nl-ams.scw.cloud/revlabs/dcron
    username: nologin
    password:
      from_secret: SCW_SECRET_KEY
    registry: rg.nl-ams.scw.cloud/revlabs
  when:
    branch:
      - master